export const theme = {
	color: {
		bgLight: "#34425D",
		bgDark: "#2B3953",
		linear: "linear-gradient(200deg, #f5af19 20%, #f12711 80%)",
		orange: "#f18701",
		white: "#fff",
		accent: "#ECF1F4",
		light: "#FAFCFE",
		success: "#31D0AA",
		error: "#EA2B2B",
	},
	text: {
		h1: {
			fontStyle: "normal",
			fontWeight: "bold",
			fontSize: "clamp(32px, 4vw + 1rem, 64px)",
			lineHeight: "clamp(36px, 4vw, 70px)",
			letterSpacing: "-0.02em",
			textTransform: "capitalize",
		},
		h2: {
			fontStyle: "normal",
			fontWeight: "bold",
			fontSize: "clamp(24px, 2vw + 1rem, 32px)",
			lineHeight: "47px",
			letterSpacing: "-0.02em",
			textTransform: "capitalize",
		},
		h3: {
			fontStyle: "normal",
			fontWeight: "bold",
			fontSize: "clamp(16px, 2vw + 1rem, 24px)",
			lineHeight: "28px",
			letterSpacing: "-0.02em",
			textTransform: "capitalize",
		},
		body: {
			fontStyle: "normal",
			fontWeight: "500",
			fontSize: "16px",
			lineHeight: "140%",
			letterSpacing: "-0.02em",
		},
		bold: {
			fontStyle: "normal",
			fontWeight: "bold",
			fontSize: "16px",
			lineHeight: "19px",
		},
		small: {
			fontStyle: "normal",
			fontWeight: "500",
			fontSize: "14px",
			lineHeight: "140%",
		},
		preTitle: {
			fontStyle: "normal",
			fontWeight: "bold",
			fontSize: "12px",
			lineHeight: "14px",
			letterSpacing: "-0.03em",
			textTransform: "uppercase",
		},
		button: {
			fontStyle: "normal",
			fontWeight: "bold",
			fontSize: "16px",
			lineHeight: "19px",
			letterSpacing: "-0.04em",
			textTransform: "uppercase",
		},
		link: {
			fontStyle: "normal",
			fontWeight: "bold",
			fontSize: "16px",
			lineHeight: "19px",
			textDecorationLine: "underline",
		},
	},
	button: {
		shadow:
			'box-shadow: "0px 6px 2px -4px rgba(14, 14, 44, 0.1), inset 0px -1px 0px rgba(14, 14, 44, 0.4)',
	},
};
