import type { NextPage } from "next";
import Head from "next/head";
import useAuth from "../hooks/useAuth";

const Home: NextPage = () => {
  const { user, error, loginWithGoogle, logout } = useAuth();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>Hello</main>
      {user && user.email}
      {error && error}
      {loginWithGoogle && (
        <button onClick={() => loginWithGoogle()}>login</button>
      )}
      {logout && <button onClick={() => logout()}>logout</button>}
      <footer></footer>
    </div>
  );
};

export default Home;
